version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.2.4
jobs:
  build:
    docker:
      - image: cimg/node:16.14.0-browsers
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/repo

    steps:
      - checkout
      - browser-tools/install-browser-tools
      - run: npm install
      - run:
        node --version
        java --version
        google-chrome --version

      # run tests!
      - run: npm test
      - run: npm run e2e-test