version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.2.4
jobs:
  build:
    working_directory: ~/repo

    steps:
      - checkout
      - browser-tools/install-browser-tools
      - run: npm install
      - run: |
          node --version
          java --version
          google-chrome --version

      # run tests!
      - run: npm test
      - run: npm run e2e-test